### ISSUE TITLE
CSV should be opened in text mode

### ISSUE THREAD

**Issue by giampaolo** [btimby/fulltext#15]
```
17/1086 /home/giampaolo/Desktop/test-data/General Company Shared/random search from archive.org/search (9).csv
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/giampaolo/svn/smartfile/duster/duster/crawler.py", line 27, in process_file
    for fp in fingerprints:
  File "/home/giampaolo/svn/smartfile/duster/duster/__init__.py", line 263, in dust
    for fn, type, size, ct, mt, raw, text in unwrap(path):
  File "/home/giampaolo/svn/smartfile/duster/duster/containers.py", line 230, in unwrap
    for item in unwrap_text(path, type):
  File "/home/giampaolo/svn/smartfile/duster/duster/containers.py", line 152, in unwrap_text
    text = fulltext.get(path, **kwargs)
  File "/home/giampaolo/svn/smartfile/fulltext/fulltext/__init__.py", line 146, in get
    backend, path_or_file, mime=mime, name=name, **kwargs)
  File "/home/giampaolo/svn/smartfile/fulltext/fulltext/__init__.py", line 82, in _get_path
    return backend._get_file(f, **kwargs)
  File "/home/giampaolo/svn/smartfile/fulltext/fulltext/backends/__csv.py", line 13, in _get_file
    for row in csv.reader(f.readlines(), dialect='excel'):
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```

**Comment by btimby** [comment]
Fixed via decoding binary to unicode.

https://github.com/btimby/fulltext/blob/master/fulltext/backends/__csv.py#L11
