### ISSUE TITLE
parameters  encoding and  encoding_errors not set

### ISSUE THREAD

**Issue by alekssamos** [btimby/fulltext#99]
`fulltext.get('foo.pdf', encoding='latin1', encoding_errors='ignore')`
The encoding was as UTF8 and remains. It doesn't change. The "encoding_errors" parameter does not work.

version from pip install: fulltext==0.5

**Comment by alekssamos** [comment]
not work epub, jpg, png.

doc, html. pdf and other  work normally

fulltext.get("book.epub")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\fulltext\__init__.py", line 154, in get
    backend, path_or_file, mime=mime, name=name, **kwargs)
  File "C:\Python37\lib\site-packages\fulltext\__init__.py", line 90, in _get_path
    return backend._get_file(f, **kwargs)
  File "C:\Python37\lib\site-packages\fulltext\backends\__text.py", line 20, in _get_file
    text = f.read(BUFFER_MAX)
  File "C:\Python37\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 166: character maps to <undefined>

**Comment by alekssamos** [comment]
Install the new version from [Github](https://github.com/btimby/fulltext/), not from [pip](https://pypi.org/project/fulltext/).
Fix:
`python -m pip install git+https://github.com/btimby/fulltext.git`
